
import {
  FileImage,
  Scan,
  Scissors,
  Text,
  FileText,
  Smile,
  Merge,
  Star,
  Type,
  ImageIcon,
  FlipHorizontal,
  Eraser,
  Bot,
  Sparkles,
  FileJson,
  Video,
  PenTool,
  Droplet,
  Crown,
  Maximize,
  RotateCcw,
  RefreshCw,
  ArrowRightLeft,
  Shield,
  FileCode,
  Brush,
  Layers,
  Wand2,
  FileMinus,
  RotateCw,
} from 'lucide-react';
import type React from 'react';

export type ToolCategory = 'Image' | 'PDF' | 'Text & AI' | 'Premium';

export interface Tool {
  name: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  path: string;
  category: ToolCategory;
  color: string;
  isAi?: boolean;
  isComingSoon?: boolean;
}

export const tools: Tool[] = [
  {
    name: 'Photo Editor',
    description: 'A full-featured editor for all your photo editing needs.',
    icon: Brush,
    path: '/tools/photo-editor',
    category: 'Image',
    color: 'text-green-500',
  },
  {
    name: 'AI Photo Editor',
    description: 'Describe your edits and let AI do the work for you.',
    icon: Wand2,
    path: '/tools/ai-photo-editor',
    category: 'Image',
    color: 'text-purple-500',
    isAi: true,
  },
  {
    name: 'Compress Image',
    description: 'Reduce image file size without losing quality.',
    icon: FileMinus,
    path: '/tools/compress-image',
    category: 'Image',
    color: 'text-blue-500',
  },
  {
    name: 'Resize Image',
    description: 'Adjust image dimensions with pixel-perfect precision.',
    icon: Maximize,
    path: '/tools/resize-image',
    category: 'Image',
    color: 'text-blue-500',
  },
  {
    name: 'Image Upscaler',
    description: 'Increase image resolution with AI enhancement.',
    icon: Star,
    path: '/tools/image-upscaler',
    category: 'Image',
    color: 'text-purple-500',
    isAi: true,
  },
  {
    name: 'Crop Image',
    description: 'Cut and frame images with custom aspect ratios.',
    icon: Scissors,
    path: '/tools/crop-image',
    category: 'Image',
    color: 'text-blue-500',
  },
   {
    name: 'Convert to JPG',
    description: 'Transform various image formats into high-quality JPGs.',
    icon: RefreshCw,
    path: '/tools/convert-to-jpg',
    category: 'Image',
    color: 'text-blue-500',
  },
  {
    name: 'Convert from JPG',
    description: 'Change JPG images to PNG, WEBP, GIF, or BMP.',
    icon: ArrowRightLeft,
    path: '/tools/convert-from-jpg',
    category: 'Image',
    color: 'text-blue-500',
  },
  {
    name: 'Background Remover',
    description: 'Automatically remove the background from any image.',
    icon: Eraser,
    path: '/tools/ai-background-remover',
    category: 'Image',
    color: 'text-purple-500',
    isAi: true,
  },
    {
    name: 'Watermark Image',
    description: 'Add a text or image watermark to your pictures.',
    icon: Layers,
    path: '/tools/watermark-image',
    category: 'Image',
    color: 'text-cyan-500',
  },
  {
    name: 'HTML to Image',
    description: 'Convert HTML code into a downloadable image file.',
    icon: FileCode,
    path: '/tools/html-to-image',
    category: 'Image',
    color: 'text-orange-500',
  },
  {
    name: 'Text Summarizer',
    description: 'Condense long articles or text into a short summary.',
    icon: Bot,
    path: '/tools/text-summarization',
    category: 'Text & AI',
    color: 'text-green-500',
    isAi: true,
  },
  {
    name: 'Meme Generator',
    description: 'Create your own memes by adding text to images.',
    icon: Smile,
    path: '/tools/meme-generator',
    category: 'Image',
    color: 'text-yellow-500',
  },
  {
    name: 'JPG to PDF',
    description: 'Convert JPG images to a single PDF file.',
    icon: FileJson,
    path: '/tools/jpg-to-pdf',
    category: 'PDF',
    color: 'text-red-500',
  },
  {
    name: 'AI Content Generator',
    description: 'Generate high-quality text content for any purpose.',
    icon: Sparkles,
    path: '/tools/ai-content-generator',
    category: 'Text & AI',
    color: 'text-green-500',
    isAi: true,
  },
   {
    name: 'Rotate Image',
    description: 'Rotate images left or right by 90 degrees.',
    icon: RotateCcw,
    path: '/tools/rotate-image',
    category: 'Image',
    color: 'text-blue-500',
  },
  {
    name: 'Blur Faces',
    description: 'Automatically detect and blur faces for privacy.',
    icon: Shield,
    path: '/tools/blur-faces',
    category: 'Image',
    color: 'text-purple-500',
    isAi: true,
  },
  {
    name: 'AI Video Enhancer',
    description: 'Improve video quality, color, and stabilization.',
    icon: Video,
    path: '/premium/ai-video-enhancer',
    category: 'Premium',
    color: 'text-amber-500',
    isAi: true,
    isComingSoon: true,
  },
  {
    name: 'Watermark Remover',
    description: 'AI-powered removal of watermarks from images.',
    icon: Droplet,
    path: '/premium/watermark-remover',
    category: 'Premium',
    color: 'text-amber-500',
    isAi: true,
    isComingSoon: true,
  },
  {
    name: 'Secure Document Signing',
    description: 'Digitally sign your PDF documents with ease.',
    icon: PenTool,
    path: '/premium/secure-document-signing',
    category: 'Premium',
    color: 'text-amber-500',
    isComingSoon: true,
  },
  {
    name: 'Brand Kit Generator',
    description: 'Create logos, color palettes, and fonts for your brand.',
    icon: Crown,
    path: '/premium/brand-kit-generator',
    category: 'Premium',
    color: 'text-amber-500',
    isAi: true,
    isComingSoon: true,
  },
];
