
import {
  FileImage,
  Scan,
  Scissors,
  Text,
  FileText,
  Smile,
  Merge,
  Star,
  Type,
  ImageIcon,
  FlipHorizontal,
  Eraser,
  Bot,
  Sparkles,
  FileJson,
  Video,
  PenTool,
  Droplet,
  Crown,
  Maximize,
  RotateCcw,
  RefreshCw,
  ArrowRightLeft,
  Shield,
  FileCode,
  Brush,
  Layers,
  Wand2,
  FileMinus,
  RotateCw,
  FileType,
  Hash,
  Tags,
  MonitorPlay,
  Calculator,
  DollarSign,
  Search,
  Crop,
} from 'lucide-react';
import type React from 'react';

export type ToolCategory = 'Image' | 'PDF' | 'Text & AI' | 'Premium';

export interface Tool {
  name: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  path: string;
  category: ToolCategory;
  color: string;
  isAi?: boolean;
  isComingSoon?: boolean;
  isNew?: boolean;
}

export const tools: Tool[] = [
  {
    name: 'Photo Editor',
    description: 'A full-featured editor for all your photo editing needs.',
    icon: Brush,
    path: '/tools/photo-editor',
    category: 'Image',
    color: 'text-green-500',
  },
  {
    name: 'AI Photo Editor',
    description: 'Describe your edits and let AI do the work for you.',
    icon: Wand2,
    path: '/tools/ai-photo-editor',
    category: 'Image',
    color: 'text-purple-500',
    isAi: true,
    isComingSoon: true,
  },
  {
    name: 'Compress Image',
    description: 'Reduce image file size without losing quality.',
    icon: FileMinus,
    path: '/tools/compress-image',
    category: 'Image',
    color: 'text-blue-500',
  },
  {
    name: 'Resize Image',
    description: 'Adjust image dimensions with pixel-perfect precision.',
    icon: Maximize,
    path: '/tools/resize-image',
    category: 'Image',
    color: 'text-blue-500',
  },
  {
    name: 'Image Upscaler',
    description: 'Increase image resolution with AI enhancement.',
    icon: Star,
    path: '/tools/image-upscaler',
    category: 'Image',
    color: 'text-purple-500',
    isAi: true,
    isComingSoon: true,
  },
  {
    name: 'Crop Image',
    description: 'Cut and frame images with custom aspect ratios.',
    icon: Scissors,
    path: '/tools/crop-image',
    category: 'Image',
    color: 'text-blue-500',
  },
  {
    name: 'Convert to JPG',
    description: 'Transform various image formats into high-quality JPGs.',
    icon: RefreshCw,
    path: '/tools/convert-to-jpg',
    category: 'Image',
    color: 'text-blue-500',
  },
  {
    name: 'Convert from JPG',
    description: 'Change JPG images to PNG, WEBP, GIF, or BMP.',
    icon: ArrowRightLeft,
    path: '/tools/convert-from-jpg',
    category: 'Image',
    color: 'text-blue-500',
  },
  {
    name: 'Background Remover',
    description: 'Automatically remove the background from any image.',
    icon: Eraser,
    path: '/tools/ai-background-remover',
    category: 'Image',
    color: 'text-purple-500',
    isAi: true,
  },
  {
    name: 'Watermark Image',
    description: 'Add a text or image watermark to your pictures.',
    icon: Layers,
    path: '/tools/watermark-image',
    category: 'Image',
    color: 'text-cyan-500',
  },
  {
    name: 'HTML to Image',
    description: 'Convert HTML code into a downloadable image file.',
    icon: FileCode,
    path: '/tools/html-to-image',
    category: 'Image',
    color: 'text-orange-500',
  },
  {
    name: 'Text Summarizer',
    description: 'Condense long articles or text into a short summary.',
    icon: Bot,
    path: '/tools/text-summarization',
    category: 'Text & AI',
    color: 'text-green-500',
    isAi: true,
  },
  {
    name: 'Notepad',
    description: 'A simple online text editor with auto-save.',
    icon: Type,
    path: '/tools/notepad',
    category: 'Text & AI',
    color: 'text-blue-500',
  },
  {
    name: 'Meme Generator',
    description: 'Create your own memes by adding text to images.',
    icon: Smile,
    path: '/tools/meme-generator',
    category: 'Image',
    color: 'text-yellow-500',
  },
  {
    name: 'YouTube Thumbnail Downloader',
    description: 'Download high-quality thumbnails from any YouTube video.',
    icon: ImageIcon,
    path: '/tools/youtube-thumbnail-downloader',
    category: 'Image',
    color: 'text-red-600',
  },
  {
    name: 'JPG to PDF',
    description: 'Convert JPG images to a single PDF file.',
    icon: FileJson,
    path: '/tools/jpg-to-pdf',
    category: 'PDF',
    color: 'text-red-500',
  },
  {
    name: 'Split PDF',
    description: 'Extract pages from your PDF.',
    icon: Scissors,
    path: '/tools/split-pdf',
    category: 'PDF',
    color: 'text-orange-500',
  },
  {
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one.',
    icon: Merge,
    path: '/tools/merge-pdf',
    category: 'PDF',
    color: 'text-purple-500',
  },
  {
    name: 'Organize PDF',
    description: 'Reorder, rotate, and remove pages.',
    icon: Layers,
    path: '/tools/organize-pdf-tool',
    category: 'PDF',
    color: 'text-blue-500',
  },
  {
    name: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality.',
    icon: FileText,
    path: '/tools/compress-pdf',
    category: 'PDF',
    color: 'text-red-500',
  },
  {
    name: 'Word to PDF',
    description: 'Convert DOCX files to PDF documents',
    icon: FileType,
    path: '/tools/word-to-pdf',
    category: 'PDF',
    color: 'bg-blue-500',
  },
  {
    name: 'PDF to Word',
    description: 'Convert PDF files to editable DOCX documents',
    icon: FileText,
    path: '/tools/pdf-to-word',
    category: 'PDF',
    color: 'bg-blue-600',
  },
  {
    name: 'AI Content Generator',
    description: 'Generate high-quality text content for any purpose.',
    icon: Sparkles,
    path: '/tools/ai-content-generator',
    category: 'Text & AI',
    color: 'text-green-500',
    isAi: true,
  },
  {
    name: 'AI Humanizer',
    description: 'Rewrite text to sound more natural and human-like.',
    icon: Sparkles,
    path: '/tools/ai-humanizer',
    category: 'Text & AI',
    color: 'text-pink-500',
    isAi: true,
  },
  {
    name: 'Plagiarism Checker',
    description: 'Analyze text for originality and robotic patterns.',
    icon: Shield,
    path: '/tools/plagiarism-checker',
    category: 'Text & AI',
    color: 'text-orange-500',
    isAi: true,
  },
  {
    name: 'Rotate Image',
    description: 'Rotate images left or right by 90 degrees.',
    icon: RotateCcw,
    path: '/tools/rotate-image',
    category: 'Image',
    color: 'text-blue-500',
  },
  {
    name: 'Blur Faces',
    description: 'Automatically detect and blur faces for privacy.',
    icon: Shield,
    path: '/tools/blur-faces',
    category: 'Image',
    color: 'text-purple-500',
    isAi: true,
    isComingSoon: true,
  },
  {
    name: 'AI Video Enhancer',
    description: 'Improve video quality, color, and stabilization.',
    icon: Video,
    path: '/premium/ai-video-enhancer',
    category: 'Premium',
    color: 'text-amber-500',
    isAi: true,
    isComingSoon: true,
  },
  {
    name: 'Watermark Remover',
    description: 'AI-powered removal of watermarks from images.',
    icon: Droplet,
    path: '/premium/watermark-remover',
    category: 'Premium',
    color: 'text-amber-500',
    isAi: true,
    isComingSoon: true,
  },
  {
    name: 'Secure Document Signing',
    description: 'Digitally sign your PDF documents with ease.',
    icon: PenTool,
    path: '/premium/secure-document-signing',
    category: 'Premium',
    color: 'text-amber-500',
    isComingSoon: true,
  },
  {
    name: 'Brand Kit Generator',
    description: 'Create logos, color palettes, and fonts for your brand.',
    icon: Crown,
    path: '/premium/brand-kit-generator',
    category: 'Premium',
    color: 'text-amber-500',
    isAi: true,
    isComingSoon: true,
  },
  {
    name: 'YouTube Transcript Extractor',
    description: 'Extract text and captions from YouTube videos.',
    icon: FileText,
    path: '/tools/youtube-transcript-extractor',
    category: 'Text & AI',
    color: 'text-red-500',
  },
  {
    name: 'YouTube Earning Calculator',
    description: 'Estimate potential YouTube revenue based on views and CPM.',
    icon: Calculator,
    path: '/tools/youtube-earning-calculator',
    category: 'Text & AI',
    color: 'text-green-500',
    isAi: false,
  },
  {
    name: 'YouTube Channel ID Finder',
    description: 'Find the unique ID of any YouTube channel from a video or link.',
    path: '/tools/youtube-channel-id-finder',
    category: 'Text & AI',
    icon: Search,
    isNew: true,
    isAi: false,
    color: 'text-blue-500',
  },
  {
    name: 'YouTube Monetization Checker',
    description: 'Check if a YouTube channel is monetized and analyze its eligibility.',
    path: '/tools/youtube-monetization-checker',
    category: 'Text & AI',
    icon: DollarSign,
    isNew: true,
    isAi: false,
    color: 'text-green-500',
  },
  {
    name: 'PDF to PowerPoint',
    description: 'Convert PDF documents to editable PowerPoint presentations with live preview.',
    path: '/tools/pdf-to-powerpoint',
    category: 'PDF',
    icon: FileText,
    isNew: true,
    isAi: false,
    color: 'text-orange-500',
  },
  {
    name: 'Crop PDF',
    description: 'Trim margins and crop pages in your PDF documents.',
    path: '/tools/crop-pdf',
    category: 'PDF',
    icon: Crop,
    isNew: true,
    isAi: false,
    color: 'text-blue-600',
  },
  {
    name: 'YouTube Tag Generator',
    description: 'Generate optimized tags for your YouTube videos to boost SEO.',
    icon: Hash,
    path: '/tools/youtube-tag-generator',
    category: 'Text & AI',
    color: 'text-red-500',
    isAi: true,
  },
  {
    name: 'YouTube Tag Extractor',
    description: 'Extract hidden tags and keywords from any YouTube video.',
    icon: Tags,
    path: '/tools/youtube-tag-extractor',
    category: 'Text & AI',
    color: 'text-blue-500',
  },
  {
    name: 'YouTube Data Viewer',
    description: 'View detailed metadata, statistics, and thumbnails for any YouTube video.',
    icon: MonitorPlay,
    path: '/tools/youtube-data-viewer',
    category: 'Text & AI',
    color: 'text-purple-500',
  },
];
